#
# Makefile for the kb drivers.
# insert (/chstime_hr to /drivers, Makefile_psr as Makefile and Kconfig) in to linux-kernel 

# Each configuration option enables a list of files.

obj-$(CONFIG_KSD_TIMER_DRIVER_HR) += mod_chsthr_fops.o
