#
# Makefile for the kb drivers.
# insert (/chstime_hr to /drivers, Makefile_prj as Makefile and Kconfig) in to linux-kernel 

# Each configuration option enables a list of files.

obj-$(CONFIG_KSD_TIMER_DRIVER_HR_MULTI) += mod_chsthr_multi_fops.o
